// AUTO-GENERATED by scripts/embed-dist.ts — do not edit by hand.
// Maps URL paths to client build files so `bun build --compile` embeds them
// into the standalone executable. Empty during normal development (the server
// falls back to reading client/dist from disk).
import f0 from "../client/dist/assets/index-DPka5qaY.js" with { type: "file" };
import f1 from "../client/dist/assets/index-TO3LUdDO.css" with { type: "file" };
import f2 from "../client/dist/index.html" with { type: "file" };

export const distFiles: Record<string, string> = {
  "/assets/index-DPka5qaY.js": f0,
  "/assets/index-TO3LUdDO.css": f1,
  "/index.html": f2,
};
