// Regenerates server/dist-manifest.ts from the current client/dist build,
// so that `bun build --compile` embeds the web client into the executable.
import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const distDir = join(import.meta.dir, "..", "client", "dist");
const outFile = join(import.meta.dir, "..", "server", "dist-manifest.ts");

if (!existsSync(join(distDir, "index.html"))) {
  console.error("client/dist/index.html not found — run `bun run build` first.");
  process.exit(1);
}

const files: string[] = [];
(function walk(dir: string) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p);
    else files.push(p);
  }
})(distDir);

let imports = "";
let entries = "";
files.forEach((p, i) => {
  const url = "/" + relative(distDir, p).replaceAll("\\", "/");
  imports += `import f${i} from ${JSON.stringify(`../client/dist${url}`)} with { type: "file" };\n`;
  entries += `  ${JSON.stringify(url)}: f${i},\n`;
});

writeFileSync(
  outFile,
  `// AUTO-GENERATED by scripts/embed-dist.ts — do not edit by hand.
// Maps URL paths to client build files so \`bun build --compile\` embeds them
// into the standalone executable. Empty during normal development (the server
// falls back to reading client/dist from disk).
${imports}
export const distFiles: Record<string, string> = {
${entries}};
`,
);

console.log(`Embedded ${files.length} client files into server/dist-manifest.ts`);
